### ISSUE TITLE
The Pypi page looks weird

### ISSUE THREAD

**Issue by pombredanne** [desbma/pyfastcopy#1]
Sounds like the ReST is garbled? https://pypi.python.org/pypi/pyfastcopy/1.0.2

**Comment by desbma** [comment]
Thanks for the report.

I use pandoc to [automatically convert the GitHub Markdown README to RST](https://github.com/desbma/pyfastcopy/blob/master/setup.py#L26) when Travis publishes the package.

Unfortunately, PyPI has limitations and sometimes refuses to display valid RST when it has images with links.

Anyway I have manually fixed the PyPI page.
